@startuml vue-implementation
package magasin {

  [controllers] as C
  [views] as V
  [templates] as T
  [urls.py] as U

  package models {
    [Magasin] as S1
    [Produit] as S2
    [Stock] as S3
    [Vente] as S4
    [ligneVente] as S5
  }

  C --> S1 : gère magasins
  C --> S2 : gère produits
  C --> S3 : gère stock
  C --> S4 : gère ventes
  C --> S5 : gère les lignes de vente
  V --> C : appelle logique
  U --> V : redirige vers
  V --> T : affiche les pages HTML
}
@enduml
