@startuml VueCasUtilisation
left to right direction
skinparam packageStyle rectangle

actor "Employé magasin" as Employe
actor "Maison mère" as Admin

package "Système de gestion de stock" {
    usecase "UC1 - Rapport des ventes" as UC1
    usecase "UC2 - Consultation stock central\n+ Demande réapprovisionnement" as UC2
    usecase "UC3 - Tableau de bord performances" as UC3
    usecase "UC4 - Gérer les produits" as UC4
    usecase "UC6 - Valider ou rejeter\nréapprovisionnement" as UC6
}

Admin --> UC1
Admin --> UC3
Admin --> UC4
Admin --> UC6

Employe --> UC2

@enduml
