@startuml VueDeploiement
skinparam componentStyle rectangle
skinparam defaultTextAlignment center
left to right direction

node "VM Étudiante" {
  node "Container : Django App" {
    component "magasin (backend Django)"
    database "PostgreSQL"
  }

  node "Container : Web Server (nginx, optional)" {
    component "Serveur HTTP\n(port 8000 ou 80)"
  }
}

cloud "DockerHub" {
  artifact "python:3.12"
  artifact "postgres:15"
}

cloud "Maison mère (navigateur)" {
  component "Interface Web"
}

"Maison mère (navigateur)" --> "Serveur HTTP\n(port 8000 ou 80)" : Requêtes HTTP
"Serveur HTTP\n(port 8000 ou 80)" --> "magasin (backend Django)" : Routage interne
"magasin (backend Django)" --> "PostgreSQL" : Requêtes ORM SQL

"python:3.12" --> "magasin (backend Django)"
"postgres:15" --> "PostgreSQL"
@enduml
